monday_academy_landing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include(('landing.urls', 'alijon'), namespace='articles')),
    path('users/', include(('users.urls', 'alijon'), namespace='users'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('sign_in', views.sign_in, name='sign_in'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('sign_out', views.sign_out, name='sign_out'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class SignUpForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class SignInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}))

    class Meta:
        model = User
        fields = ['username', 'password']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .forms import *


def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('users:sign_in')
    form = SignUpForm()
    return render(request, 'sign_up.html', {'form': form})

def sign_in(request):
    if request.method == 'POST':
        form = SignInForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if "next" in request.POST:
                return redirect(request.POST.get ("next"))
            return redirect('articles:article_list')
    form = SignInForm()
    return render(request, 'sign_in.html', {'form': form})

def sign_out(request):
    logout(request)
    return redirect('users:sign_in')

users/templates/sign_in.html
{% extends "base_layout.html" %}

{% block content %}
<form class="site-form has-background-light has-text-dark " method="post">
    <div class="title has-text-centered size-2 has-text-dark">Sign in</div>
    {% csrf_token %}
    {% for field in form %}
    <div class="field">
        <label class="label" for="{{ field.id_for_label }}">{{ field.html_name }}</label>
        {{field}}
        {% for error in field.errors %}
        <p class="help is-danger">{{ error }}</p>
        {% endfor %}
    </div>
    {% endfor %}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <button type="submit" class="button is-warning is-fullwidth my-3">Войти</button>
    <p class='has-text-centered has-text-grey is-size-6'>
        Don't have an account?
        <a href="{% url 'users:sign_up' %}">Sign up here</a>
    </p>
</form>
{% endblock %}

users/templates/sign_up.html
{% extends "base_layout.html" %}

{% block content %}
<form class="site-form has-background-light has-text-dark " method="post">
    <div class="title has-text-centered size-2 has-text-dark">Sign up</div>
    {% csrf_token %}
    {% for field in form %}

    <div class="field">
        <label class="label" for="{{ field.id_for_label }}">{{ field.html_name }}</label>
        {{field}}
        {% for error in field.errors %}
        <p class="help is-danger">{{ error }}</p>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" class="button is-warning is-fullwidth my-4">Войти</button>
    <p class='has-text-centered has-text-grey is-size-6'>
        Already have an account?
        <a href="{% url 'users:sign_in' %}">Sign in here</a>
    </p>
</form>
{% endblock %}