landing/urls.py
from . import views
from django.urls import path

urlpatterns = [
   path('', views.home, name='article_list'),
   path('create_article', views.create_article, name='article_create'),
   path('<slug>', views.article_detail, name='article_detail'),
   path('<slug>/edit', views.edit_article, name='edit_article'),
   path('<slug>/delete', views.delete_article, name='delete_article'),
   path('<slug>/likes', views.like_article, name='like_article'),
   path('<slug>/dislikes', views.dislike_article, name='dislike_article'),
   path('<slug>/comment/<pk>/delete', views.delete_comment, name='delete_comment'),
   path('<slug>/comment/<pk>/edit', views.edit_comment, name='edit_comment')
]

monday_academy_landing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include(('landing.urls', 'alijon'), namespace='articles')),
    path('users/', include(('users.urls', 'alijon'), namespace='users'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('sign_in', views.sign_in, name='sign_in'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('sign_out', views.sign_out, name='sign_out'),
]

landing/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField('Заголовок',max_length=255)
    text = models.TextField('Содержимое')
    slug = models.SlugField('Ссылка')
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField('Картинка', default='default.jpg', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='article_likes')
    dislikes = models.ManyToManyField(User, related_name='article_dislikes')

    def __str__(self):
        return self.title

    def snippet(self):
        return self.text[:20] + '... read more'

    def shorten(self):
        return self.title[:10] + '...'

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    body = models.TextField()

    def __str__(self):
        return '%s - %s' % (self.article, self.body[:5])

landing/forms.py
from django import forms
from . import models

class ArticleForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))
    text = forms.CharField(widget=forms.TextInput(attrs={'class': 'textarea', 'size': '40'}))
    slug = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))

    class Meta:
        model = models.Article
        fields = ['title', 'text', 'slug', 'thumb']

class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'textarea',
        'size': '40',
        'placeholder': 'Write your comment here',
    }))

    class Meta:
        model = models.Comment
        fields = ['body', ]

landing/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Article, Comment
from . import forms
from django.db.models import Q


@login_required(login_url='/users/sign_in')
def home(request):
    search = request.GET.get('search')
    articles = Article.objects.all().order_by('date')
    articles = articles.filter(Q(title__icontains=search) | Q(text__icontains=search)) if search else articles
    return render(request, 'home.html', {'articles': articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    if request.method == 'POST':
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.article = article
            instance.save()
            return redirect('articles:article_detail', slug=slug)
    else:
        form = forms.CommentForm()
    return render(request, 'article_detail.html', {'article': article, 'form': form})


def create_article(request):
    if request.method == 'POST':
        form = forms.ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:article_list')
    form = forms.ArticleForm()
    return render(request, 'create_article.html', {'form': form})


def edit_article(request, slug):
    article = Article.objects.get(slug=slug)
    form = forms.ArticleForm(request.POST or None,
                             request.FILES or None, instance=article)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('articles:article_detail', slug=request.POST.get('slug'))
    return render(request, 'edit_article.html', {'form': form, 'article': article})


def delete_article(request, slug):
    article = Article.objects.get(slug=slug)

    if request.method == 'POST':
        article.delete()
        return redirect('articles:article_detail', slug=slug)
    return render(request, 'delete_comment.html', {'comment': comment})

def edit_comment(request, slug, pk):
    comment = Comment.objects.get(pk=pk)
    form = forms.CommentForm(request.POST or None, instance=comment)
    if form.is_valid():
        form.save()
        return redirect('articles:article_detail', slug=slug)
    return render(request, 'edit_comment.html', {'form': form, 'article': comment.article})
        

def delete_comment(request, slug, pk):
    comment = Comment.objects.get(pk=pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('articles:article_detail', slug=slug)
    return render(request, 'delete_comment.html', {'comment': comment})


def like_article(request, slug):
    article = Article.objects.get(slug=slug)

    if request.user not in article.likes.all():
        article.likes.add(request.user)
        article.dislikes.remove(
            request.user) if request.user in article.dislikes.all() else None
    elif request.user in article.likes.all():
        article.likes.remove(request.user)
    return redirect('articles:article_detail', slug=slug)


def dislike_article(request, slug):
    article = Article.objects.get(slug=slug)

    if request.user not in article.dislikes.all():
        article.dislikes.add(request.user)
        article.likes.remove(
            request.user) if request.user in article.likes.all() else None
    elif request.user in article.dislikes.all():
        article.dislikes.remove(request.user)
    return redirect('articles:article_detail', slug=slug)

landing/templates/article_detail.html
{% extends 'base_layout.html' %}
{% load static from static %}


{% block content %}
<div class="box">
    <div class="has-text-right">
        {% if user == article.author %}
        <a href="{% url 'articles:edit_article' article.slug %}" class="button">
            <ion-icon name="create-outline" style="color: blue; width: 26px; height: 26px;"></ion-icon>
        </a>
        <a href="{% url 'articles:delete_article' article.slug %}" class="button">
            <ion-icon name="trash-outline" style="color: red; width: 26px; height: 26px;"></ion-icon>
        </a>
        {% else %}
        <b>You can not edit or delete this post</b>
        {% endif %}
    </div>
    <div class="title has-text-dark has-text-centered">{{ article }}</div>
    <img src="{{article.thumb.url}}" alt="" class="image is-centered" style="min-width: 100%; border-radius: 5px">
    <div class="subtitle has-text-dark has-text-centered">{{ article.text }}</div>
    <div class="has-text-right is-italic">
        Date of publication {{article.date}}
        <br>
        {% if article.author == user %}
        <b>Published by you</b>
        {% else %}
        <b>Published by {{article.author}}</b>
        {% endif %}
        {% if user not in article.likes.all and user not in article.dislikes.all %}
        <div class="columns">
            <div class="column is-1">
                <form action="{% url 'articles:like_article' article.slug %}" method="post" class="has-text-right">
                    {% csrf_token %}
                    <button type="submit" class="button">
                        <ion-icon name="thumbs-up-outline"></ion-icon>
                        <span class="ml-2">{{ article.total_likes }}</span>
                    </button>
                </form>
            </div>
            <div class="column is-1">
                <form action="{% url 'articles:dislike_article' article.slug %}" method="post" class="has-text-right">
                    {% csrf_token %}
                    <button type="submit" class="button">
                        <ion-icon name="thumbs-down-outline"></ion-icon>
                        <span class="ml-2">{{ article.total_dislikes }}</span>
                    </button>
                </form>
            </div>
        </div>
        {% endif %}
        {% if user in article.likes.all and user not in article.dislikes.all %}
        <div class="columns">
            <div class="column is-1">
                <form action="{% url 'articles:like_article' article.slug %}" method="post" class="has-text-right">
                    {% csrf_token %}
                    <button type="submit" class="button is-success">
                        <ion-icon name="thumbs-up-outline"></ion-icon>
                        <span class="ml-2">{{ article.total_likes }}</span>
                    </button>
                </form>
            </div>
            <div class="column is-1">
                <form action="{% url 'articles:dislike_article' article.slug %}" method="post" class="has-text-right">
                    {% csrf_token %}
                    <button type="submit" class="button">
                        <ion-icon name="thumbs-down-outline"></ion-icon>
                        <span class="ml-2">{{ article.total_dislikes }}</span>
                    </button>
                </form>
            </div>
        </div>
        {% endif %}
        {% if user not in article.likes.all and user in article.dislikes.all %}
        <div class="columns">
            <div class="column is-1">
                <form action="{% url 'articles:like_article' article.slug %}" method="post" class="has-text-right">
                    {% csrf_token %}
                    <button type="submit" class="button">
                        <ion-icon name="thumbs-up-outline"></ion-icon>
                        <span class="ml-2">{{ article.total_likes }}</span>
                    </button>
                </form>
            </div>
            <div class="column is-1">
                <form action="{% url 'articles:dislike_article' article.slug %}" method="post" class="has-text-right">
                    {% csrf_token %}
                    <button type="submit" class="button is-danger">
                        <ion-icon name="thumbs-down-outline"></ion-icon>
                        <span class="ml-2">{{ article.total_dislikes }}</span>
                    </button>
                </form>
            </div>
        </div>
        {% endif %}
    </div>
    {% if not article.comment_set.all %}
        <div class="has-text-centered has-text-grey-light is-size-5 mx-3">
            No comments!
        </div>
    {% else %}
        {% for comment in article.comment_set.all %}
            <article class="message is-info">
                <div class="message-header">
                    {% if user == comment.user %}
                    Added by you at {{ comment.date_added }}
                    <div class="has-text-right is-size-5">
                        <a href="{% url 'articles:edit_comment' slug=article.slug pk=comment.pk %}" style="text-decoration: none" class="is-info">
                            <ion-icon name="create-outline"></ion-icon>
                        </a>
                        <a href="{% url 'articles:delete_comment' slug=article.slug pk=comment.pk %}" class="is-info">
                            <ion-icon name="trash-outline"></ion-icon>
                        </a>
                    </div>
                    {% else %}
                    Added by {{ comment.user }} at {{ comment.date_added }}
                    {% endif %}                   
                </div>
                <div class="message-body">
                    {{ comment.body }}
                </div>
            </article>
        {% endfor %}
    {% endif %}
    <form method="post" enctype="multipart/form-data" class="comment">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="button is-success mt-3 is-fullwidth">Отправить</button>
    </form>
    {% endblock %}
</div>

landing/templates/base_layout.html
{% load static from static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">
    <link rel="stylesheet" href="{% static 'all.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</head>

<section class="hero has-background-info is-fullheight">
    <div class="hero-head">
        <header class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a class="navbar-item" href="{% url 'articles:article_list' %}">
                        <img src="../../media//monday.svg" width="100" alt="Logo">
                    </a>
                    <span class="navbar-burger" data-target="navbarMenuHeroC">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </div>
                <div id="navbarMenuHeroC" class="navbar-menu">
                    {% if user.is_authenticated %}
                    <div class="navbar-start">
                        <span class="navbar-item">
                            <a href="{% url 'articles:article_create' %}" class="button has-text-weight-bold is-info is-inverted is-outlined">
                                <span class="mr-2">
                                    <ion-icon name="book-outline"></ion-icon>
                                </span>
                                Создать пост
                            </a>
                        </span>
                    </div>
                    <div class="navbar-end">
                        <form action="{% url 'articles:article_list' %}" method="get">
                            <div class="field has-addons mt-4 mr-2">
                                <div class="control">
                                    <input type="search" class="input" placeholder="Find an article" name="search">
                                </div>
                                <div class="control">
                                    <button class="button is-primary" type="submit">
                                        Search
                                    </button>
                                </div>
                            </div>
                        </form>
                        <button class="navbar-item button has-text-dark my-4 mx-1">
                            Welcome: {{user}}
                        </button>
                        <a href="{% url 'users:sign_out' %}" class="navbar-item button is-danger my-4 mx-1">Sign out</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </header>
    </div>
    <div class="hero-body">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</section>

</html>

landing/templates/create_article.html
{% extends "base_layout.html" %}

{% block content %}
<form class="site-form has-background-light" action="{% url 'articles:article_create' %}" method="post" enctype="multipart/form-data">
    <div class="title has-text-centered is-size-4 has-text-weight-bold">Создать пост</div>
    {% csrf_token %}
    {% for field in form %}

    <div class="field">
        <label class="label" for="{{ field.id_for_label }}">
            {{ field.label }}
        </label>
        {{ field }}
    </div>

    {% endfor %}
    <div class="has-text-centered my-2">
        <button type="submit" class="button is-success">Отправить</button>
        <a href="{% url 'articles:article_list' %}" class="button is-danger">Отмена</a>
    </div>
    
</form>
{% endblock %}

landing/templates/delete_article.html
{% extends "base_layout.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="columns is-centered">
            <div class="column is-6">
                <div class="notification">
                    <p class="content has-text-dark is-size-4 has-text-centered">Вы действительно хотите удалить пост "{{article.title}}"?</p>
                    <div class="has-text-centered">
                        <button type="submit" class="button is-primary">Подтвердить</button>
                        <a href="{% url 'articles:article_detail' article.slug %}" class="button is-danger">Отмена</a>
                    </div>    
                </div>        
            </div>
        </div>
        
    </form>
{% endblock %}

landing/templates/delete_comment.html
{% extends "base_layout.html" %}

{% block content %}
    <form method="post" class="site-form has-background-light">
        {% csrf_token %}
        <p class="content is-size-4 mb-4">Хотите удалить комментарий?</p>
        <div class="has-text-centered">
            <button type="submit" class="button is-primary">Подтвердить</button>
            <a href="{% url 'articles:article_detail' slug=comment.article.slug %}" class="button is-danger">Отмена</a>
        </div>
    </form>
{% endblock %}

landing/templates/edit_article.html
{% extends "base_layout.html" %}

{% block content %}
<form class="site-form has-background-light" method="post" enctype="multipart/form-data">
    <div class="title has-text-centered is-size-4 has-text-weight-bold">Изменить пост</div>
    {% csrf_token %}
    {{form}}
    <div class="has-text-centered my-2">
        <button type="submit" class="button is-warning">Отправить</button>
        <a href="{% url 'articles:article_detail' article.slug %}" class="button">Отмена</a>
    </div>
    
</form>
{% endblock %}

landing/templates/edit_comment.html
{% extends "base_layout.html" %}

{% block content %}
    <form method="post" class="site-form has-background-light">
        {% csrf_token %}
        {{ form }}
        <div class="has-text-centered mt-4">
            <button type="submit" class="button is-primary">Подтвердить</button>
            <a href="{% url 'articles:article_detail' slug=article.slug %}" class="button is-danger">Отмена</a>
        </div>
    </form>
{% endblock %}

landing/templates/home.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
<div class="container">
    <div class="columns is-multiline is-centered">
        {% for article in articles %}
        <div class="column is-3">
            <a href="{% url 'articles:article_detail' article.slug %}">
                <div class="card is-centeredrf">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title has-text-dark has-text-weight-bold is-4 has-text-centered">
                                    {{ article.shorten }}
                                </p>
                                <p class="subtitle is-4 has-text-grey has-text-centered">by {{ article.author }}</p>
                            </div>
                        </div>
                        <div class="content has-text-centered">
                            {{ article.snippet }}
                            <br>
                            <div>{{ article.date }}</div>
                        </div>
                        <div class="columns">
                            <div class="column is-2">
                                <div class="columns is-gapless">
                                    <div class="column">
                                        <ion-icon name="thumbs-up-outline"></ion-icon>
                                    </div>
                                    <div class="column">
                                        <span class="ml-2">{{ article.total_likes }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="column is-2">
                                <div class="columns is-gapless">
                                    <div class="column">
                                        <ion-icon name="thumbs-down-outline"></ion-icon>
                                    </div>
                                    <div class="column">
                                        <span class="ml-2">{{ article.total_dislikes }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}